version: 2

updates:
  - package-ecosystem: "github-actions"
  - package-ecosystem: "pip"
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    assignees:
      - "melvyndekort"
    reviewers:
      - "melvyndekort"
